# This is a basic workflow to help you get started with Actions

name: Sync Fork

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/10 * * * *'
    
  repository_dispatch:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fork Sync
      # You may pin to the exact commit or the version.
      # uses: tgymnich/fork-sync@0cc6ac48fd51415e7c34e5b8823021bc952a5f5f
        uses: tgymnich/fork-sync@v1.2.1
        with:
          # Owner of the forked repository
          owner: misar-naeem
          # Token for the github API
          github_token: ${{ secrets.FORK_API_SECRET }}
          # Branch to track
          head: main
          # Branch to keep updated
          base: main
